<Project>
    <!-- Build.targets file evaluated after .csrpoj file processing -->
    <PropertyGroup Label="Common">
        <!-- XML documentation, depends on AssemblyName from .csrpoj -->
        <DocumentationFile>$(TargetDir)\$(AssemblyName).xml</DocumentationFile>

    </PropertyGroup>

    <!-- KOMSA origin marker, linked into every assembly built from this folder -->
    <ItemGroup>
        <Compile Include="$(MSBuildThisFileDirectory)KomsaSharedAssemblyInfo.cs" Link="Properties\KomsaSharedAssemblyInfo.cs" />
    </ItemGroup>
</Project>
